server:
  port: 8102

#Кастомные конфигурации для топика-источника и групп консьюмеров kafka
custom-kafka:
  payment-topic: 'payments'
  consumer-notification-group: 'notification-group'
  consumer-statistics-group: 'statistics-group'

#Включение\выключение отправки уведомления на почту клиента
mail-sender:
  enabled: true

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
  #Настройки для отправки уведомлений на почту через почтовый сервер yandex
  mail:
    host: smtp.yandex.ru
    username: notifyService1@yandex.ru
    password: ulftraxzhyyaypxu
    port: 465
    protocol: smtps
